### ISSUE TITLE
遊び方の追加

### ISSUE THREAD

**Issue by tamagram** [chikyu-gakko/kanjiou#143]
# 概要
各ゲームモードで遊び方がついていないところがある  
ない場所には追加する

**Comment by tamagram** [comment]
@set2002satoshi のコメント待ち

**Comment by set2002satoshi** [comment]
説明文は地球学校さんの方で直すってことだったので、すぐにハメ込めるようなデザインテンプレートしか作ってないです。

**Comment by tamagram** [comment]
#162 
で修正するためclose
