### ISSUE TITLE
UI改善

### ISSUE THREAD

**Issue by ghost** [chikyu-gakko/kanjiou#150]
# 概要
各ゲームの機能追加などを行ってきたがUIが崩れている部分がある
- 何問中難問 -> x/x問
- テキストをアイコンにできるところはアイコンする
- 看板の表示を完璧に
などを修正

**Comment by tamagram** [comment]
その他修正点
- 羊の中に犬が１匹
  - ゲームモードの選択画面で上から羊、世界、仲間の順番でボタンを並べる
- 世界の文字
  - どこの国 -> 何語？　に変更
- 仲間であつまれ
   - 設定画面で下のように表示する
     - レベル１　小学１～３年生　⇒　％
     - レベル２　小学４～６年生
     - レベル３　小学１～６年生
