### ISSUE TITLE
UIをXDに近づける

### ISSUE THREAD

**Issue by tamagram** [chikyu-gakko/kanjiou#76]
# 概要

# 受け入れ条件(AC)

# TODO

TODOをやる際の相談点

デザインカンプでは全体のボタンのボーダー太く作られているがゲームだと細い件
ボタンが写真ぽいのですが、これは修正できます?

## UIの修正が必要な箇所をリストアップする
ランキング表ページ
- ランキング表の上のボタンが2個しかないから5個に増やす
- ランキング表の上のボタンの全体的に大きいため修正する
- ランキングの見出しと王冠を追加する。
-  ランキングテーブル表の横幅の比率を修正する。

ランキング入りした際の名前を入力するモーダル
- ランキング数字が強調されてない
- ランキング王冠がない
- 文字のフォントが汚い（デザインカンプでは細い字）
-  textareaの背景色が青？ぽい
-  登録ボタンが地味（もっと横に長くて縦幅が細い）
-  Xボタンが太いまる位置がおかしい 

ゲームクリアページ
- フォントがきもい
- ボタンが地味

## リスアップされたUIを修正する
ランキング表ページ
- [x] ランキング表の上のボタンが2個しかないから5個に増やす
- [x] ランキング表の上のボタンの全体的に大きいため修正する
- [x] ランキングの見出しと王冠を追加する。
- [x] ランキングテーブル表の横幅の比率を修正する。

ランキング入りした際の名前を入力するモーダル
- [ ] ランキング数字が強調されてない
- [x] ランキング王冠がない
- [x] 文字のフォントが汚い（デザインカンプでは細い字）
- [x] textareaの背景色が青？ぽい
- [x] 登録ボタンが地味（もっと横に長くて縦幅が細い）
- [x] Xボタンが太いまる位置がおかしい
- [ ] XDのデザインのようにモグラがいる場所にモグラを追加する

**Comment by set2002satoshi** [comment]
# 概要

# 受け入れ条件(AC)


# TODO

TODOをやる際の相談点

デザインカンプでは全体のボタンのボーダー太く作られているがゲームだと細い件
ボタンが写真ぽいのですが、これは修正できます?

## UIの修正が必要な箇所をリストアップする
ランキング表ページ
- ランキング表の上のボタンが2個しかないから5個に増やす
- ランキング表の上のボタンの全体的に大きいため修正する
- ランキングの見出しと王冠を追加する。
-  ランキングテーブル表の横幅の比率を修正する。
ランキング入りした際の名前を入力するモーダル
- ランキング数字が強調されてない
- ランキング王冠がない
- 文字のフォントが汚い（デザインカンプでは細い字）
-  textareaの背景色が青？ぽい
-  登録ボタンが地味（もっと横に長くて縦幅が細い）
-  Xボタンが太いまる位置がおかしい
ゲームクリアページ
- フォントがきもい
- ボタンが地味

## リスアップされたUIを修正する
ランキング表ページ
- [ ] ランキング表の上のボタンが2個しかないから5個に増やす
- [ ] ランキング表の上のボタンの全体的に大きいため修正する
- [ ] ランキングの見出しと王冠を追加する。
- [ ] ランキングテーブル表の横幅の比率を修正する。

ランキング入りした際の名前を入力するモーダル
- [ ] ランキング数字が強調されてない
- [ ] ランキング王冠がない
- [ ] 文字のフォントが汚い（デザインカンプでは細い字）
- [ ] textareaの背景色が青？ぽい
- [ ] 登録ボタンが地味（もっと横に長くて縦幅が細い）
- [ ] Xボタンが太いまる位置がおかしい

ゲームクリアページ
- [ ] フォントがきもい
- [ ] ボタンが地味

**Comment by tamagram** [comment]
ボタンの枠が細いのはボタンを作るためのクラスをいじれば直せそうな気もするが、写真でしか無理そうなであれば一旦置いておく
